import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryClientProviderComponent from "@/providers/QueryClientProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<QueryClientProviderComponent>
				<AuthProvider>
					<body className={inter.className}>
						{children}
						<ReactQueryDevtools initialIsOpen={false} />
					</body>
				</AuthProvider>
			</QueryClientProviderComponent>
		</html>
	);
}
